import { build } from 'esbuild';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
await mkdir(new URL('dist/vendor/', root), { recursive: true });
await build({ entryPoints: [new URL('scripts/avatar-entry.js', root).pathname], outfile: new URL('dist/vendor/avatar.js', root).pathname, bundle: true, minify: true, format: 'esm', platform: 'browser', target: 'es2020', legalComments: 'eof', banner: { js: '// DiceBear Core + Avataaars 9.2.4. See avatar-LICENSE.txt. Generated by scripts/build-avatar.mjs.' } });
let licenses = '';
for (const name of ['@dicebear/core', '@dicebear/avataaars']) licenses += `\n${name} 9.2.4\n\n${await readFile(new URL(`node_modules/${name}/LICENSE`, root), 'utf8')}\n`;
await writeFile(new URL('dist/vendor/avatar-LICENSE.txt', root), licenses);
